-- Let's Play minimally live dashboard schema
-- Run in the Supabase SQL Editor for the project's public prototype.

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  anonymous_session_id uuid not null,
  event_type text not null check (
    event_type in (
      'session_started',
      'screen_viewed',
      'screen_completed',
      'answer_selected',
      'lesson_completed'
    )
  ),
  screen_number integer check (screen_number is null or screen_number >= 0),
  language text not null default 'ar' check (char_length(language) between 2 and 12),
  metadata jsonb not null default '{}'::jsonb,
  constraint metadata_is_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists learning_events_created_at_idx
  on public.learning_events (created_at desc);

create index if not exists learning_events_session_idx
  on public.learning_events (anonymous_session_id, created_at desc);

alter table public.learning_events enable row level security;

drop policy if exists "anonymous users can insert learning events" on public.learning_events;
create policy "anonymous users can insert learning events"
  on public.learning_events
  for insert
  to anon
  with check (
    char_length(event_type) between 3 and 40
    and pg_column_size(metadata) <= 4096
  );

drop policy if exists "anonymous users can read dashboard events" on public.learning_events;
create policy "anonymous users can read dashboard events"
  on public.learning_events
  for select
  to anon
  using (true);

grant select, insert on public.learning_events to anon;
grant usage, select on sequence public.learning_events_id_seq to anon;

-- Add the table to the Realtime publication if it is not already present.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'learning_events'
  ) then
    alter publication supabase_realtime add table public.learning_events;
  end if;
end $$;
